// Darkest Dungeon II metinlerinin Türkçesi (Babuşlar için çevrildi). Kahraman, yol, beceri ve boss adları ile oyun
// terimleri (Stress, Burn, Combo…) İngilizce bırakıldı. Yol metinlerindeki simge etiketleri (<span class="tok">) korunmuştur.
const DKD2_TR = {
  heroes: {
    Abomination: { quote: "Dövülmüş ve dağlanmış bu serseri göründüğünden daha tehlikeli…", description: "Utançla zincirlenmiş, öfkeyle serbest kalmış." },
    "Bounty Hunter": { quote: "Avın heyecanı, ödülün vaadi!" },
    Crusader: { quote: "Metal ve insan, asker ve kılıç: savaşın ateşinde dövülmüş.", description: "Kutsal savaşın ateşinde dövülmüş. Türünün son temsilcisi." },
    Duelist: { quote: "Kusursuzluk, meç'in ucunda kötücül bir parıltıyla parlar.", description: "Kusursuzluk acıma bilmez." },
    Flagellant: { quote: "Bağnazlık: ruhta hiç ölmeyen bir çürüme.", description: "Acıya ve cezaya karşı hiç ölmeyen bir iştah." },
    "Grave Robber": { quote: "Açgözlülük, zihnin yeraltı mezarlarına fark edilmeden sızar.", description: "Çevik, zarif ve eşsiz derecede sinsi." },
    Hellion: { quote: "Kan hırsının ve öfkenin altında bir boşluk… ve utanç var.", description: "Kan dökmek: tanrılara bir adak!" },
    Highwayman: { quote: "Avlanan, telaşlı; geçmişinden kaçmaya çalışan bir kaçak.", description: "Şiddetle çok yönlü, acımasızca pratik." },
    Jester: { quote: "Son akor vurulduktan çok sonra bile öldürücü bir melodi kulaklarda kalır.", description: "Lavta ve bıçakla ateşli bir şekilde çalınan zincirsiz melodiler." },
    Leper: { quote: "Zorlukla barışmak, varoluşun ta kendisidir.", description: "Acı kabul edildiğinde güç bolca akar." },
    "Man-at-Arms": { quote: "Gurur: yüz seferin dehşetinden daha yıkıcı.", description: "Sayısız saldırının acımasız darbeleriyle pişmiş kararlı bir savunucu." },
    Occultist: { quote: "Uçurumu tanımak için onu kucaklamak gerekir.", description: "Boşluğun cehennemi ve küfürbaz gücüne tanık ol!" },
    "Plague Doctor": { quote: "Ayrım gözetmeyen bilim cerrahın ellerini lekeler.", description: "Hekim dediğin, çürümenin öğrencisinden başka nedir ki?" },
    Runaway: { quote: "Hiçbir şey kalmadı… hayatta kalmak için yanan bir irade dışında.", description: "Ateş ve duman: yıkım ve gizlenme." },
    Vestal: { quote: "Bir savaş rahibesi: dışlanmış ama boyun eğmemiş!", description: "İnanç, tövbekâr kalbi tutuşturan bir ateştir!" },
  },

  // Yollar (Path): "Kahraman/Yol". Wanderer her kahramanda varsayılan beceri setidir.
  paths: {
    "Abomination/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Abomination/Unchained": "Dostlarını desteklerken düşman savunmalarını uzaktan aşındıran hareketli bir savaşçı.",
    "Abomination/Fiend": "Bleed veren ve ondan yararlanan, bunu da kendine ağır bir bedelle yapan vahşi bir canavar.",
    "Abomination/Moribund": "Stresin ezici ağırlığından güç alan, önüne geleni yıkan bir yaratık.",
    "Bounty Hunter/Professional": "Bounty Hunter'ın tek bir yolu vardır, <b>Professional</b>; ek bir etkisi yoktur.",
    "Crusader/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Crusader/Aggressor": "<span class=\"nowrap\"><span class=\"tok\">Burn</span><span class=\"burn-dd2\">kutsal ateşle</span></span> arındırıp öldüren bir ön saf savaşçısı.",
    "Crusader/Templar": "Yaralarını iyileştirirken dostlarını koruyan, kendine yeten bir savunucu.",
    "Crusader/Banneret": "Menzili artmış, iyileştirme ve geniş alan güçlendirmeleri yapabilen zırhlı bir destekçi.",
    "Duelist/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.<br>Duruş pasifleri <span class=\"tok\">Riposte</span> ile hayatta kalmayı güçlendirir.<br><span class=\"tok\">Riposte</span> yapınca:<br>* <span class=\"tok\">Aggressive Stance</span>: Kendini %10 iyileştir (%33)<br>* <span class=\"tok\">Defensive Stance</span>: <span class=\"tok\">Dodge</span> kazan (%33)",
    "Duelist/Instructrice": "Bedeli ne olursa olsun dostlarını ileri süren bir arka saf eğitmeni. Duruş pasifleri öldürücü darbede toparlanma sağlar.<br>Öldürücü darbede:<br>* <span class=\"tok\">Aggressive Stance</span>: <span class=\"nowrap\"><span class=\"tok\">Regeneration</span><span class=\"heal-dd2\">3</span></span><br>* <span class=\"tok\">Defensive Stance</span>: <span class=\"nowrap\"><span class=\"buff-dd2\">-1</span> <span class=\"tok\">Stress</span></span>",
    "Duelist/Antagoniste": "Düşmanı bozmakta ustadır; dostlarının yararlanacağı açıklar yaratır. Duruş pasifleri <span class=\"tok\">Debuff</span> RES'i deler ya da zayıflatır.<br><span class=\"tok\">Aggressive Stance</span>: <span class=\"nowrap\"><span class=\"buff-dd2\">+%15</span> <span class=\"tok\">Debuff</span> RES delme</span><br><span class=\"tok\">Defensive Stance</span>: Kılıç becerileri: <span class=\"nowrap\"><span class=\"debuff-dd2\">-%5</span> <span class=\"tok\">Debuff</span> RES</span> (3 tur)<br>\"Kılıç becerileri\": Touché, Feint, Disengage, Flick, Flèche, <i>Riposte Attack</i> ve <i>Act-Out Attack</i>.<br><span class=\"tok\">Defensive Stance</span> zayıflatmasına <span class=\"tok\">Riposte</span> dışında direnilemez.",
    "Duelist/Intrépide": "Her sıradan oynanabilen, çok yüksek riskli ve yüksek hasar potansiyelli bir rol. Duruş pasifleri gücü ve riski birlikte artırır, 5 kata kadar birikir. Hasar alınca etkiler kaybolur.<br>Iskalanınca kazan:<br>* <span class=\"tok\">Aggressive Stance</span>: +%5 CRIT, <span class=\"nowrap\"><span class=\"debuff-dd2\">-%10</span> <span class=\"tok\">Damage over Time</span> RES</span><br>* <span class=\"tok\">Defensive Stance</span>: +%20 verilen DMG, +%40 alınan DMG",
    "Flagellant/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Flagellant/Maniac": "Esnek konumlanma, zayıflatma ve düzen bozma için <span class=\"tok\">Blight</span> gücünden fedakârlık eder.",
    "Flagellant/Exanimate": "Düşük can, <span class=\"tok\">Blight</span>'a ve güçlendirmelere büyük güç katar.",
    "Flagellant/Scourge": "Başkalarının yüklerini üstlenmekten zevk alan bir rol. Toxic durumu yeni etkiler kazanır.",
    "Grave Robber/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Grave Robber/Deadeye": "CRIT'e ve menzile ağırlık veren bir arka saf rolü.",
    "Grave Robber/Venomdrop": "Grave Robber'ın <span class=\"tok\">Blight</span> yeteneklerini genişleten, her sıradan oynanabilen bir rol.",
    "Grave Robber/Nightsworn": "<span class=\"tok\">Stealth</span> odaklı çeşitli saldırı ve savunma kırma becerilerine sahip esnek bir rol.",
    "Hellion/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.<br><span class=\"tok\">HP</span> %66'nın altındayken: +%25 DMG<br><span class=\"tok\">HP</span> %33'ün altındayken: +%25 DMG",
    "Hellion/Ravager": "Ölümün gözünün içine korkusuzca bakan, savunma kıran bir rol.<br><span class=\"tok\">HP</span> %66'nın altındayken +%25 DMG<br><span class=\"tok\">HP</span> %33'ün altındayken <span class=\"tok\">Winded</span>'ı yok say<br>Death's Door cezalarını yok sayar<br>Öldürücü darbede: <span class=\"nowrap\"><span class=\"heal-dd2\"><span class=\"tok\">HP</span> %25 iyileş</span></span> (cesetlere karşı işe yaramaz)",
    "Hellion/Berserker": "Tempoyu korumak için CRIT'lerden yararlanan esnek bir rol.<br><span class=\"tok\">HP</span> %66'nın altındayken +%10 CRIT<br><span class=\"tok\">HP</span> %33'ün altındayken <span class=\"nowrap\"><span class=\"buff-dd2\">+1</span> verilen <span class=\"tok\">Bleed</span> süresi</span><br>CRIT yapınca: <span class=\"tok\">Winded</span>'ı yok say (1 tur)",
    "Hellion/Carcass": "Büyük cezalara göğüs geren bir ön saf rolü.<br><span class=\"tok\">HP</span> %33'ün altındayken +%20 <span class=\"tok\">Damage over Time</span><span class=\"tok\">Move</span><span class=\"tok\">Stun</span><span class=\"tok\">Debuff</span> RES<br>CRIT yapınca: 0-2 <span class=\"tok\">Stress</span> iyileş<br>Tur sonu: Her <span class=\"tok\">Winded</span> için <span class=\"tok\">Block</span> kazan (%66)",
    "Highwayman/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.<br>Riposte <span class=\"tok\">Combo</span> verir (%33).",
    "Highwayman/Rogue": "Ön saf dövüşüne ve <span class=\"tok\">Riposte</span>'lara odaklanan bir kavgacı.<br>Riposte <span class=\"tok\">Combo</span> verir (%33).",
    "Highwayman/Sharpshot": "Menzilli becerilere ağırlık veren bir arka saf rolü.<br>Riposte <span class=\"tok\">Combo</span> verir (%33).",
    "Highwayman/Yellowhand": "Her sıradan oynanabilen bir Bleed uzmanı.<br>Riposte <span class=\"nowrap\"><span class=\"tok\">Bleed</span><span class=\"bleed-dd2\">2</span></span> verir.",
    "Jester/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Jester/Virtuoso": "Takım desteği ve stres önlemede uzmanlaşan bir rol.<br>Encore artık ek hamle vermez; bunun yerine tüm dostlara (Jester hariç) birkaç güçlendirme verir.<br>Battle Ballad, Echoing March, Inspiring Tune, Play Out ve Solo, bir sonraki Encore'a güçlendirme ekler.",
    "Jester/Soloist": "Ani hasar ve kendini toparlamada uzmanlaşan bir rol.<br>Finale, Battle Ballad, Play Out ve Harvest'tan bonus alır.<br>Iskalanınca kazan:<br>* <span class=\"tok\">Buff</span> (savaş sonuna kadar):<br>** Yakın dövüş becerileri: +1 DMG<br>** Sonraki Finale: +2 DMG<br>* <span class=\"tok\">Buff</span> en fazla 3 kez birikir.",
    "Jester/Intermezzo": "Sesin gücünü herkes için tehlikeli seviyelere yükselten bir rol.",
    "Leper/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Leper/Tempest": "Kendini korumayı pek umursamadan, kaotik hareketlerini olumsuz token'lardan alan bir rol.",
    "Leper/Poet": "Sarsılmaz ve yılmaz bir savunma rolü.",
    "Leper/Monarch": "Uzun seferlerde parlayan, ön saflardan liderlik eden bir rol.<br>Bazı beceriler, sefer boyunca biriken bir <span class=\"tok\">Buff</span> olan <b>Monarch's Oath</b> ile güçlenir.<br>Öldürücü darbede Monarch's Oath kazan:<br>* +%1<br>* Bosslara karşı +%3<br>* İn (Lair) bosslarına karşı +%6<br>* Cesetlere karşı işe yaramaz<br>Kalıcı olarak, en fazla %66'ya kadar birikir.<br>Hareket İleri 2, Geri 2 olur.",
    "Man-at-Arms/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Man-at-Arms/Sergeant": "Savunma ve saldırı destek emirlerini karıştırmada uzmanlaşan bir rol.<br>Bazı beceriler arka saflardan kullanılabilen güçlendirmelere dönüşür.",
    "Man-at-Arms/Bulwark": "Kontrol ve destek becerileriyle tanklık yapmaya odaklanan bir rol.<br>Riposte <span class=\"tok\">Daze</span> verir (%33).<br>Bazı beceriler <span class=\"tok\">Block</span>/<span class=\"tok\">Block+</span> ile güçlenir.",
    "Man-at-Arms/Vanguard": "Artan güç için savunmadan fedakârlık eden bir rol.<br>Courageous Abandon ve Riposte her kullanıldığında biriken <span class=\"tok\">Buff</span> ve <span class=\"tok\">Debuff</span>'lar kazanır; bunlara <i>Vanguard güçlendirme ve zayıflatmaları</i> denir.<br>Bellow ve Stand Fast da bunlarla etkileşir.",
    "Occultist/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Occultist/Ritualist": "Direnç pahasına lanetlerde ve destekte uzmanlaşan bir rol.<br>Her <span class=\"tok\">Unchecked Power</span> için:<br>* <span class=\"nowrap\"><span class=\"buff-dd2\">+%10</span> <span class=\"tok\">Debuff</span> RES delme</span><br>* <span class=\"nowrap\"><span class=\"debuff-dd2\">-%10</span> <span class=\"tok\">Debuff</span> RES</span>",
    "Occultist/Warlock": "Hayatta kalma pahasına saldırıyı güçlendiren bir rol.<br>Her <span class=\"tok\">Unchecked Power</span> için:<br>* +1 DMG<br>* +%10 alınan DMG",
    "Occultist/Aspirant": "Yakın dövüşe ve DoT çeşitliliğine ağırlık veren hareketli bir rol.<br>Hareket edince: <span class=\"tok\">Unchecked Power</span> (%70)<br>Her token için hareket edince <span class=\"tok\">Unchecked Power</span> kazanma ihtimali %20 azalır",
    "Plague Doctor/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Plague Doctor/Surgeon": "Incision'a ve kendini savunma seçeneklerine ağırlık veren yakın mesafe rolü. Öldürücü darbede kazan: <span class=\"nowrap\"><span class=\"tok\">Regeneration</span><span class=\"heal-dd2\">2</span></span>",
    "Plague Doctor/Alchemist": "<span class=\"tok\">Bleed</span>, <span class=\"tok\">Blight</span> ve <span class=\"tok\">Burn</span>'ü ölümcül etkiyle karıştıran bir rol.",
    "Plague Doctor/Physician": "Dostları güçlendirmede ve düşmanları zayıflatmada eşit ölçüde uzmanlaşan bir rol.",
    "Runaway/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.",
    "Runaway/Arsonist": "Alevlerden zevk alan, kendini de başkalarını da ayrım gözetmeden yakan bir rol. Arsonist'in kendine Burn veren becerilerine direnilemez ve DoT değiştiricilerinden etkilenir. Tur sonu: Arsonist'te <span class=\"tok\">Burn</span> varsa <span class=\"nowrap\"><span class=\"buff-dd2\">+1</span> verilen <span class=\"tok\">Burn</span></span> ve <span class=\"nowrap\"><span class=\"buff-dd2\">+2</span> <span class=\"tok\">Speed</span></span> kazanır, 3 kata kadar birikir. Bir tur bittiğinde Arsonist'te <span class=\"tok\">Burn</span> yoksa bu güçlendirmeler kaybolur.",
    "Runaway/Survivor": "Ön saf yeteneklerini güçlendiren ve ani etkiler için <span class=\"tok\">Stealth</span> harcayan bir rol. İyileştikten sonra HP hâlâ %75'in altındaysa: <span class=\"tok\">Dodge</span> (%50) ya da <span class=\"tok\">Dodge+</span> (%25) kazan.",
    "Runaway/Orphan": "Doğrudan hasarı ve <span class=\"tok\">Burn</span>'ü etkilemek için konumlanmaya dayanan bir rol.<br>Tur başı: Bulunduğu sıra <i>Stable</i> (sabit) olur.<br>Tur sonu:<br>* Sabit sırada 1 tur kalınca <span class=\"nowrap\"><span class=\"buff-dd2\">+1</span> verilen <span class=\"tok\">Burn</span></span>.<br>* Sabit sırada 2 tur kalınca <span class=\"nowrap\"><span class=\"buff-dd2\">+1</span> verilen <span class=\"tok\">Burn</span> süresi</span>.<br>* Turu başka bir sırada bitirirse bu güçlendirmeler kaybolur.<br>Hareket edince: +1 DMG kazanır, 2 kata kadar birikir.<br>* Orphan bir turda hareket etmezse bu güçlendirmeler kaybolur.",
    "Vestal/Wanderer": "Varsayılan beceriler. İkinci hana ulaşınca <span class=\"tok\">Candles of Hope</span> kazandırır.<br>Tur başı: <span class=\"tok\">Conviction</span>",
    "Vestal/Confessor": "Zayıflatmalarda ve token kaldırmada uzmanlaşan, her sıradan oynanabilen bir rol.<br>Tur başı: <span class=\"tok\">Conviction</span><br>Her <span class=\"tok\">Conviction</span> için: <span class=\"nowrap\"><span class=\"buff-dd2\">+%5</span> <span class=\"tok\">Debuff</span> RES delme</span>",
    "Vestal/Chaplain": "Takım savunmasına odaklanan bir ön saf rolü.<br>Vurulunca: <span class=\"tok\">Conviction</span><br>CRIT yiyince: <span class=\"tok\">Conviction</span> (%60)<br>Her <span class=\"tok\">Conviction</span> için:<br>* <span class=\"nowrap\"><span class=\"buff-dd2\">+%10</span> <span class=\"tok\">Stun</span> RES</span><br>* <span class=\"nowrap\"><span class=\"buff-dd2\">+%10</span> <span class=\"tok\">Move</span> RES</span>",
    "Vestal/Seraph": "Consecration'larda uzmanlaşan bir arka saf destek rolü.<br>Bir Consecration etkinleşince: <span class=\"tok\">Conviction</span><br>Consecration'lar 5 tur sürer.",
  },

  bosses: {
    "Ancient Adversary": {
      intro: "Ancient Adversary, Darkest Dungeon II'nin gizli bir bossudur.",
      behavior: "Uğursuz bir güç yayan, tanıdık bir figürün dev taş heykeli. Takımda en az bir olumsuz ilişki varsa, Assistance Encounter'larda, Oasis'lerde ve Creature Den'lerde %5 ihtimalle \"Enduring Evil\" adlı özel bir seçenek olarak çıkar.\nAncient Adversary ile dövüşmeyi seçersen dövüş 5 tur sonra kendiliğinden biter (Kingdoms'ta geri çekilme seçeneği de yoktur) ve koşunun geri kalanında bir daha çıkmaz.",
    },
    Antiquarian: {
      quote: "Bir zamanlar bir parça edebi vardı… şimdi yalnızca açgözlülük.",
      intro: "Antiquarian, Darkest Dungeon II'de bir Pillager bossudur. Envanter en az %70 doluyken herhangi bir Pillager yol savaşında ~%10 ihtimalle çıkar.",
      behavior: "Bir savaşçı olmasa da kurnaz taktikleri ve aldatıcı tütsüleriyle bunu fazlasıyla telafi eder. Çeşitli egzotik buharlarla müttefiklerini güçlendirir, düşmanlarının kafasını karıştırır; kendini savunmak zorunda kalırsa bir hançeri vardır, ama onu kullanma fikri bile onu tedirgin eder. Savaşta yenilse bile her seferinde kaçmayı başarır; kahramanlar onu asla tamamen öldüremez. Antiquarian'ı açgözlülük yönlendirir ve genellikle avı büyük bir servet taşırken saldırır.",
    },
    Archduke: {
      intro: "Archduke, bir Bloodsucker düşmanıdır ve Darkest Dungeon II'nin Curse of the Court modülünün son bossudur.",
      behavior: "Archduke'un becerilerinin çoğu, Curse of the Court modülüne özgü bir hastalık olan Crimson Curse etrafında döner.\nThe Blood Thickens: Direnç artar, Decorous Dance yerine Wasting Waltz gelir; The Blood Surges ile kalkar.\nThe Blood Surges: Turda 1 ek hamle kazanır, Decorous Dance yerine Severing Steps gelir; The Blood Thickens ile kalkar.\nFoul Blood Goblet / Pure Blood Goblet: Kadeh, Crimson Curse'lü ya da lanetsiz bir kahramanın kanını içerir.\nBlood Bloat: Noblesse Oblige ile hedeflenemez.\nBu turda hiç Goblet token'ı yoksa tur başında 1 Chosen Target token'ı çıkar; token'ın yeri değiştirilemez.",
    },
    "Body of Work": {
      quote: "Şimdi büyük başarına bak: tüm başarısızlıklarının toplamı. Senin Body of Work'ün.",
      intro: "Body of Work, 5. Perde'nin bossu ve Darkest Dungeon II'nin son bossudur. Üç aşamadan oluşur.",
    },
    Cardinal: {
      intro: "Cardinal, Darkest Dungeon II'de Cosmic/Cultist türünde bir bosstur.",
      behavior: "Cardinal korkutucu bir rakiptir. Tüm saldırıları Stress verir, birçoğu aynı anda birden fazla kahramanı vurur ve takımı Shuffle ile olumsuz token'larla dağıtır. Tek hedefli tek saldırısı Hollow Vessel, özellikle ağır zamana yayılmış hasar verir.\nDiğer Cultist bossları gibi Cardinal da müritleri tarafından tapınılabilir; bu ona en güçlü saldırısı Exultation'ı kullanma imkânı verir.",
    },
    Chirurgeon: {
      intro: "Chirurgeon (genelde Gaunt Chirurgeon diye bilinir), Darkest Dungeon II'de Chirurgeon's Table'da Patient'larla birlikte karşılaşılan bir Gaunt mini-bossudur. Öldürüldüğünde Patient'lar sonraki 3 bölgede Gaunt yol savaşlarında da çıkar.",
      behavior: "Chirurgeon'ın destekleyici de saldırgan da tüm becerileri, yanındakilerde gördüğü hastalıkları tedavi etme amacıyla yapılıyor gibidir. Bu tedaviler bazen işe yarar: Leucotomy Gaunt \"hastalarını\" hem iyileştirir hem güçlendirir, Bloodletting kahramanlardaki Disease'i gerçekten tedavi eder. Ama bazıları felaketle sonuçlanır: Trephination ve Trepanation sırasıyla müttefiklerindeki ve düşmanlarındaki olumsuz token'ları temizler, ama kaldırılan her token için ciddi hasar verir; Trepanation kahramanların aklı için de son derece stresli bir deneyimdir.",
    },
    Deacon: {
      intro: "Deacon, Darkest Dungeon II'de Cosmic/Cultist türünde bir bosstur.",
      behavior: "Deacon'lar, Cardinal gibi Cultist hizbinin en üst rütbelilerindendir. Heybetli görünüşleri ve dev savaş baltaları, hafife alınmayacak düşmanlar olduklarını hatırlatır. Büyük miktarda hasara dayanırken oyuncunun yiyeceği en acı saldırılardan bazılarını yaparlar. Kendi etlerini şekillendirerek bazı saldırı türlerinden daha az hasar alabilirler. Cardinal ve Exemplar gibi Deacon'lar da daha zayıf müttefikleri tarafından tapınılabilir; bu onları hem iyileştirir hem de yıkıcı saldırılara erişim verir.",
    },
    Death: {
      quote: "Ölüm vücut buldu ve hiçbir inkâra katlanmayacak.",
      intro: "Death, Darkest Dungeon II'de Flagellant'ın peşine düşen bir bosstur.",
      behavior: "Flagellant takımdayken, Death bir Resistance Encounter'ın ya da bölgesel düşmanlarla (Pillager, Cultist, Gaunt ya da Military olmayan) bir yol savaşının sonunda %6 ihtimalle çıkar.\nYok edilemeyen ve hedeflenemeyen iki Gravestone (mezar taşı) ile gelir. Bazı becerileri onu mezar taşlarının arasından geriye taşır; arka saflardayken tüm takıma Shuffle, Bleed ve Stress veren yıkıcı Trample'ı kullanır.\nSaldırılarıyla ağır Bleed verir; canı azaldıkça kanayan hedeflere karşı ek hasar kazanır.\nBleed'e çok dayanıklıdır, Blight ve Burn'e karşı daha az. Üzerine çok fazla zamana yayılmış hasar biriktirmek tehlikeli olabilir: Soul Reaver mevcut etkilerini Combo'lu herhangi bir kahramana aktarmasını sağlar.",
    },
    "Dreaming General": {
      quote: "Kâbus dolu bir uykuya kilitlenmiş; gerçek ve hayali başarısızlıklar ona işkence ediyor.",
      intro: "Dreaming General, The Tangle'daki kalesinde bulunan Cadaver bossudur.",
      behavior: "Yüz savaşın ateşinde dövülmüş zırhlı bir dev; bir zamanlar insanların şampiyonu, dağın tarikatçılarıyla savaş meydanında karşılaşıp yozlaşmanın önünü kesecek yetenekli bir taktisyen ve savaşçıydı. Ne yazık ki o gün hiç gelmedi. Kılıç ve okla savaşılamayan bir lanetle zihninin duvarları arasına hapsolmuş, başarısızlığının işkencesiyle uyumaya devam ediyor. Acısına son ver ve ruhuna özlediği huzuru bağışla.\nDreaming General, The Tangle'ın bölge bossudur. Yüksek hasarlı tek ve çok hedefli saldırıları ve stres saldırıları vardır. Yanında Tap Root bulunur; Tap Root, zamana yayılmış hasar veren ve hedefi takımı strese sokan bir beceriyi kullanmaya zorlayan özel bir token verebilir.",
    },
    Exemplar: {
      intro: "Exemplar, Darkest Dungeon II'de Cosmic/Cultist türünde bir bosstur.",
      behavior: "Exemplar, 3. Perde'den itibaren son bölgede, handan hemen önce Oblivion's Rampart'ta çıkar. İki varlık gibi görünür: Grotesk bir et yığınından çıkan başsız, insansı bir gövde; omurgasının ucunda Deacon ve Cardinal'ınkine benzer demir bir maske. İki \"yarısı\" farklı becerileri yönetir gibidir.\nExemplar bir kapı bekçisidir; oyuncunun The Mountain'a ulaşmadan önce güçlü düşmanları alt edebildiğinden emin olur. Saldırıları çok hasarlıdır, birden çok kahramanı hedefleyebilir ve büyük doğrudan hasar ile birlikte çeşitli olumsuz etkiler verir.\nKarşılaşmaya bir Altar ile başlar; Cultist müritlerini öldürüp yeniden çağırabilir ve bunu yaparken kendini güçlendirir.",
    },
    "Focused Fault": {
      quote: "Takıntının hiç geri çekilmeyen bakışı, kusur derecesinde odaklanmış!",
      intro: "Focused Fault, Darkest Dungeon II'de Obsession perdesinin son bossudur. Ortasında daha büyük tek bir göz bulunan, sivri dişlerle çevrili dev bir insan gözü kümesidir. Dövüş iki bölümdür: önce dört Cluster of Eyes ile, sonra Focused Fault'un kendisiyle.",
    },
    "Harvest Child": {
      quote: "Şişman, yarı yenmiş bir anneden doğan bu çocuk, yozlaşmanın açgözlü bir vücut bulmuş halidir!",
      intro: "Harvest Child, The Foetor'daki Harvest House'ta bulunan Plague Eater bossudur.",
    },
    Leviathan: {
      quote: "Onlara canavar tanrılarının ölümlü olduğu gösterilmeli.",
      intro: "Leviathan, The Shroud'daki Sacred Pier'de bulunan Fisherfolk bossudur.",
      behavior: "Leviathan iki parçalı bir bosstur: Leviathan'ın kendisi ve çağırdığı Leviathan's Hand (el). Leviathan genellikle arka saflarda kalır ve aynı anda birden çok kahramana Stress ve Debuff veren saldırılar kullanır.\nTehlikenin çoğu elden gelir: el bir kahramanı okyanusa sürükleyip savaştan çıkarabilir; o kahraman her tur yavaşça HP kaybeder ve Stress biriktirir. Ayrıca elin turda birden çok hamlesi vardır, ağır hasar verir ve her saldırısında Shuffle uygular. Eli yok etmek yakalanan kahramanı kurtarır, ama Leviathan bir sonraki turun sonunda onu yeniden çağırır.",
    },
    Librarian: {
      quote: "Merdiveninin tepesinde çılgınca sallanıyor, insanlığın başarılarının alevler içinde yok oluşundan zevk alıyor!",
      intro: "Librarian, The Sprawl'daki Great Library'de bulunan Fanatic bossudur.",
      behavior: "Librarian hareketli bir merdivenin tepesinde oturur, kitapları yakar ve sayfalarını takıma fırlatır. Diğer Fanatic'ler gibi çok fazla Burn hasarı verir ve savunması için büyük ölçüde Blind ve Dodge token'larına güvenir. Dövüşe üç kitap yığınıyla çevrili başlar. Hepsini yakınca kendini tutuşturur (Ignite); bu en güçlü yeteneği Burning Bright'ı açar ve kahramanları da alevlerle yutmakla tehdit eder.",
    },
    "Meat Hook": {
      behavior: "Beastmen'in reisi olan dev Meat Hook, bir kolunu kaybetmiş, diğerinde adını aldığı ağır bir kanca taşıyan devasa bir Rot Claw'a benzer. Savaşta yanında bir et stoğu vardır; etrafında kıyamet koparken pervasızca ondan tıkınır.\nMeat Hook, dayanıklılık ve token yönetimi üzerine oldukça düz bir dövüştür. Öndeki kahramanlara sürekli yüksek hasar ve olumsuz etkiler verir; kancası ve güçlü kükremeleriyle takımın dizilimini bozarak savunmasız kahramanları menziline çekmeye çalışır. Arada et direğinden ısırıklar alır; et direği her tur ona saldırı ve savunma token'ları üretir. Boss çalmadan önce direğin token'ları temizlenebilir; ama en az bir token kalmazsa boss ek öfke token'ları üretir. Turda birden çok hamlesi vardır ve güçlenmiş yetenekleri yıkıcı olabilir.",
    },
    "Mother of Threads": {
      intro: "Mother of Threads, Darkest Dungeon II'nin Secrets of the Coven modülünün son bossudur.",
      behavior: "Mother of Threads, bir Mother's Spitter ile ve She Who Weaves kişiliğinde başlar; her 3 turda bir kişilik değiştirir.\nShe Who Weaves: Becerilerde olumsuz token etkilerini açar.\nShe Who Severs: Hasarı artırır ve becerilerde çekme / geri itme etkilerini açar.\nHer kişilik becerileri değiştirir; hasarı ya da düzen bozmayı artırır.",
    },
    "Ravenous Reach": {
      quote: "Hırsın uzanışı, korkunç kavrayışını hep aşar!",
      intro: "Ravenous Reach, Darkest Dungeon II'nin Ambition itirafının son bossudur.",
      behavior: "Ravenous Reach, bossu güçlendiren çok sayıda olumlu token üreten bir kollar yığınıdır. 3 aşaması vardır ve her aşama bossu hasar ve menzil bakımından daha tehlikeli hale getirir.\nBastard's Beacon: Bossa özel bir değiştirici veren bir Infernal Flame.",
    },
    "Seething Sigh": {
      quote: "Seething Sigh: Pek de gizlenemeyen öfkenin hırıltılı vücut bulmuş hali!",
      intro: "Seething Sigh, Darkest Dungeon II'nin Resentment itirafının son bossudur.",
      behavior: "Seething Sigh, kanat biçimli büyük bir çift akciğere bağlı yılan benzeri bir nefes borusuna benzer; bir ejderhanın biçimini andırır. 'Boynunda' Iron Crown'un metal bir tasmasını taşır.\nBastard's Beacon: Bossa özel bir değiştirici veren bir Infernal Flame.",
    },
    Shambler: {
      intro: "Shambler, Darkest Dungeon II'de tehlikeli bir Cosmic bosstur.",
      behavior: "Shambler iki şekilde karşına çıkabilir: Academic's Study'deki Shambler's Altar'da çağrılabilir ya da sonraki bölgelerde Flame seviyesi 30 veya altındayken (Catacombs ya da Sluice'ta 50 veya altında) herhangi bir yol savaşının yerine küçük bir ihtimalle geçer. Bir sefer boyunca birden çok kez çıkabilir.\nDövüşün ana özelliği, sürekli çağırdığı Shambler Tentacle'larıdır. Her dokunaç her başarılı saldırıda kendini güçlendirir; takım ya bir dokunacı öldürüp yerine yenisinin gelmesine katlanmak ya da dokunaçların zamanla daha tehlikeli olmasına izin vermek arasında seçim yapmak zorunda kalır.\nShambler ihtimali, Flame seviyesini düşük tutmanın tehlikesini büyük ölçüde artırır. Yeterince güçlü takımlar onun eşsiz trinket'larından birini ve Mastery puanı kazanmak için Shambler ile dövüşmeyi seçebilir.",
    },
    "The Collector": {
      quote: "Uğursuz Kral yeni bir ganimet arıyor…",
      intro: "The Collector, Darkest Dungeon II'de gezgin bir bosstur.",
      behavior: "Stagecoach'a bir Trophy takılıyken takımı pusuya düşürebilen tehlikeli bir düşmandır. Military olanlar hariç her yol savaşının yerine %5 ihtimalle geçer; Collector's Chandelier takılıysa bu ihtimal %9,5'e çıkar.\nGeldiğinde üç Collected Head çağırır. Collector kahramanlara orta düzeyde hasar verir, Taunt ve Combo uygular; böylece yardımcıları Stun ve büyük miktarda Bleed verebilir. Öldürülen her Collected Head'i yeniden çağırabilir.\nYenildiğinde güçlü bir trinket, değerli hazineler (Bauble) ve belki de eşsiz bir teslimat eşyası bırakır.",
    },
    "The Shackles of Denial": {
      quote: "Zihin, kendi kendine kurduğu hapisten kurtarılmalı!",
      intro: "The Shackles of Denial, Darkest Dungeon II'nin Denial perdesinin son bossudur.",
      behavior: "Dünyanın zihni, kendi emriyle hapsolmuş. Onu bağlayan kendi zincirleri tarafından korunur; kahramanlara güçlü darbeler, çok sayıda Debuff ve Stun ile saldırır. Her turun başında zincirlerden biri kahramanların bir beceri türünü (yakın dövüş, menzilli, iyileştirme ya da stres) engeller; oyuncu hazırlıklı değilse kahramanlar Pass (tur atlama) yapmak zorunda kalabilir.",
    },
    Warlord: {
      quote: "Baltası haraç, ruhu acı istiyor…",
      intro: "Warlord, Darkest Dungeon II'de The Binding Blade DLC'sine özel bir Military bossudur.",
      behavior: "Warlord, yüksek temel hasarı ve çok sayıda alan saldırısı olan devasa bir düşmandır. Diğer Military düşmanlar gibi hasarı neredeyse yalnızca ön saflara verir ve saldırılarıyla sık sık Bleed ve Combo uygular. Ayrıca kahramanlara Daze, Stun ya da Weak verebilir, müttefiklerini Strength, Crit ve Speed ile güçlendirebilir.\nKendisi ya da müttefikleri yeterince Combo uyguladığında, herhangi bir kahramanı Death's Door'a düşürebilen yıkıcı bir savurma saldırısı olan Ferox Impetus'u kullanabilir.\nİlk kez The Lost Crusade görevinin sonunda dövüşülür. Crusader açıldıktan ve tüm kahraman tapınakları tamamlandıktan sonra herhangi bir Military yol savaşında rastgele çıkabilen gezgin bir boss olur. Karşılaşma ihtimali her bölgede artar: 1. bölgede %5, 2. bölgede %15, 3. bölgede %25. Ancak bir seferde yalnızca bir kez karşına çıkabilir.\nWarlord genellikle ön saflarda doğar; her zaman en az bir başka Military düşmanla, bazen de bir Weapon Rack ile birlikte gelir.",
    },
  },
};
