// CS2 haritaları: infolar (callout) ve bölgelere göre smoke / flash / molotof atışları (lineup).
// Konumlar radar görüntüsü üzerinde 0–1 arası oran olarak (x: soldan, y: üstten).
// Doğuş ve bomba bölgesi konumları oyunun radar dosyalarından alınmıştır.
//
// Atışlar (lineups): site "A" | "B" | "Mid", type "smoke" | "flash" | "molly".
//   yt:   [YouTube video kimliği, başlangıç sn, bitiş sn] — videonun yalnızca o kısmı oynar.
//   clip: "clips/dosya.mp4" — kendi kaydımız (reklamsız). Varsa yt yerine bu kullanılır.

const CS2_MAPS = [
  {
    id: "mirage",
    name: "Mirage",
    radar: "radar/mirage.png",
    summary: "Fas temalı klasik harita. Orta (Mid) kontrolü iki bölgeyi de açar.",
    spawns: { T: [0.87, 0.36], CT: [0.28, 0.7] },
    sites: { A: [0.54, 0.76], B: [0.23, 0.28] },
    callouts: [
      { name: "T Spawn", at: [0.88, 0.3], desc: "Teröristlerin doğduğu yer." },
      { name: "T Ramp", at: [0.84, 0.57], desc: "T doğuşundan A'ya inen yol." },
      { name: "A Ramp", at: [0.72, 0.66], desc: "Ramp'in A bölgesine açılan ucu." },
      { name: "Palace", at: [0.76, 0.76], desc: "A'ya güneyden açılan bina; balkondan A görülür." },
      { name: "Tetris", at: [0.62, 0.66], desc: "Ramp'in sonundaki kutular; A'ya girişte ilk saklanma yeri." },
      { name: "Ninja", at: [0.6, 0.83], desc: "A bölgesinin Palace tarafındaki gizli köşe." },
      { name: "Firebox", at: [0.46, 0.83], desc: "A bölgesinin CT tarafındaki kutu." },
      { name: "Stairs", at: [0.48, 0.7], desc: "A'dan Jungle ve Connector'a çıkan merdiven." },
      { name: "Jungle", at: [0.42, 0.6], desc: "A'nın kuzeybatısındaki oda; CT'lerin A savunma yeri." },
      { name: "Ticket Booth", at: [0.39, 0.8], desc: "CT ile A arasındaki bilet gişesi." },
      { name: "Connector", at: [0.51, 0.57], desc: "Mid'i Jungle ve A'ya bağlayan koridor." },
      { name: "Top Mid", at: [0.68, 0.42], desc: "Mid'in T tarafındaki girişi." },
      { name: "Mid", at: [0.56, 0.47], desc: "Haritanın ortası; A ve B arasında geçiş sağlar." },
      { name: "Window", at: [0.43, 0.44], desc: "Mid'e bakan keskin nişancı penceresi." },
      { name: "Short", at: [0.5, 0.24], desc: "Mid'den B'ye giden kısa yol (Catwalk)." },
      { name: "B Apps", at: [0.38, 0.18], desc: "B'ye giden apartman koridoru." },
      { name: "Van", at: [0.17, 0.22], desc: "B bölgesindeki minibüs; Apps çıkışını kontrol eder." },
      { name: "Market", at: [0.25, 0.45], desc: "B ile CT arasındaki dükkân." },
    ],
    lineups: [
      { site: "A", type: "smoke", name: "CT (Ticket) smoke", yt: ["AKuqMLnB07U", 63, 77], by: "CS Tactics" },
      { site: "A", type: "smoke", name: "Stairs smoke", yt: ["AKuqMLnB07U", 77, 85], by: "CS Tactics" },
      { site: "A", type: "smoke", name: "Jungle / Connector smoke", yt: ["AKuqMLnB07U", 85, 97], by: "CS Tactics" },
      { site: "A", type: "flash", name: "A bölgesi flash'ı", yt: ["u4iqihJis2k", 52, 99], by: "CS Tactics" },
      { site: "A", type: "flash", name: "A Ramp flash'ı", yt: ["u4iqihJis2k", 99, 154], by: "CS Tactics" },
      { site: "A", type: "molly", name: "Sandwich molotofu", yt: ["7P-Y_SSDFKI", 34, 46], by: "CS Tactics" },
      { site: "A", type: "molly", name: "Jungle molotofu", yt: ["7P-Y_SSDFKI", 46, 60], by: "CS Tactics" },
      { site: "A", type: "molly", name: "Dark molotofu (Palace'tan)", yt: ["7P-Y_SSDFKI", 6, 23], by: "CS Tactics" },
      { site: "B", type: "smoke", name: "B smoke'ları tek noktadan", yt: ["Su7RXe5XrXw", 0, 25], by: "ERORE" },
      { site: "B", type: "flash", name: "B bölgesi flash'ı", yt: ["u4iqihJis2k", 154, 215], by: "CS Tactics" },
      { site: "B", type: "flash", name: "B Apps flash'ı", yt: ["u4iqihJis2k", 215, 253], by: "CS Tactics" },
      { site: "Mid", type: "smoke", name: "Window smoke", yt: ["AKuqMLnB07U", 4, 25], by: "CS Tactics" },
      { site: "Mid", type: "smoke", name: "Connector smoke", yt: ["AKuqMLnB07U", 25, 45], by: "CS Tactics" },
      { site: "Mid", type: "smoke", name: "Top Mid'den Window, Short, Jungle, CT", yt: ["AKuqMLnB07U", 45, 63], by: "CS Tactics" },
      { site: "Mid", type: "flash", name: "Mid'e kendi flash'ın", yt: ["u4iqihJis2k", 253, 302], by: "CS Tactics" },
    ],
  },
  {
    id: "dust2",
    name: "Dust 2",
    radar: "radar/dust2.png",
    summary: "En bilinen harita. Uzun koridorlar ve net bölgeler; Long ve Tunnels kontrolü önemli.",
    spawns: { T: [0.39, 0.91], CT: [0.62, 0.21] },
    sites: { A: [0.8, 0.16], B: [0.21, 0.12] },
    callouts: [
      { name: "T Spawn", at: [0.38, 0.86], desc: "Teröristlerin doğduğu yer." },
      { name: "Outside Long", at: [0.61, 0.78], desc: "T doğuşundan Long kapılarına giden açık alan." },
      { name: "Long Doors", at: [0.7, 0.61], desc: "Long'a açılan çift kapı." },
      { name: "Pit", at: [0.88, 0.63], desc: "Long'un sonundaki çukur; A'ya bakan sniper yeri." },
      { name: "Long A", at: [0.88, 0.44], desc: "A bölgesine giden uzun koridor." },
      { name: "A Car", at: [0.92, 0.29], desc: "Long'un A'ya açıldığı yerdeki araba." },
      { name: "Goose", at: [0.86, 0.09], desc: "A bölgesinin arka köşesi." },
      { name: "Short", at: [0.59, 0.37], desc: "Mid'den A'ya çıkan merdivenli yol (Catwalk)." },
      { name: "Mid", at: [0.47, 0.55], desc: "Haritanın ortası; Short ve B'ye geçiş sağlar." },
      { name: "Xbox", at: [0.49, 0.42], desc: "Mid'deki büyük kutu; Short'a çıkışta kullanılır." },
      { name: "Mid Doors", at: [0.46, 0.31], desc: "Mid'i CT'ye bağlayan kapılar." },
      { name: "Top Mid", at: [0.46, 0.72], desc: "Mid'in T tarafındaki girişi." },
      { name: "Lower Tunnels", at: [0.33, 0.4], desc: "Mid'den B tünellerine giden alt tünel." },
      { name: "Upper Tunnels", at: [0.15, 0.45], desc: "B'ye açılan üst tünel." },
      { name: "Outside Tunnels", at: [0.15, 0.7], desc: "T doğuşundan tünellere giden yol." },
      { name: "B Doors", at: [0.25, 0.23], desc: "B'yi CT tarafına bağlayan kapı." },
      { name: "Window", at: [0.27, 0.12], desc: "B bölgesine CT tarafından bakan pencere." },
      { name: "Back Plat", at: [0.11, 0.05], desc: "B bölgesinin en arkası." },
    ],
    lineups: [
      { site: "A", type: "smoke", name: "CT smoke", yt: ["Bc0WFG-fU4w", 36, 74], by: "CS Tactics" },
      { site: "A", type: "smoke", name: "Long Cross smoke", yt: ["rKWeOfcTN44", 265, 299], by: "CS Tactics" },
      { site: "A", type: "smoke", name: "Long Corner smoke", yt: ["rKWeOfcTN44", 231, 265], by: "CS Tactics" },
      { site: "A", type: "smoke", name: "Short smoke'ları", yt: ["Bc0WFG-fU4w", 74, 132], by: "CS Tactics" },
      { site: "A", type: "flash", name: "Long flash'ları", yt: ["rKWeOfcTN44", 546, 641], by: "CS Tactics" },
      { site: "A", type: "flash", name: "Short (Cat) flash'ları", yt: ["rKWeOfcTN44", 641, 728], by: "CS Tactics" },
      { site: "A", type: "molly", name: "Car molotofu", yt: ["rKWeOfcTN44", 800, 819], by: "CS Tactics" },
      { site: "A", type: "molly", name: "A bölgesi molotofu", yt: ["rKWeOfcTN44", 819, 851], by: "CS Tactics" },
      { site: "B", type: "smoke", name: "B Doors smoke", yt: ["Bc0WFG-fU4w", 163, 200], by: "CS Tactics" },
      { site: "B", type: "smoke", name: "Window smoke", yt: ["Bc0WFG-fU4w", 155, 163], by: "CS Tactics" },
      { site: "B", type: "smoke", name: "B girişi smoke'ları", yt: ["rKWeOfcTN44", 439, 470], by: "CS Tactics" },
      { site: "B", type: "flash", name: "B flash'ları", yt: ["rKWeOfcTN44", 742, 800], by: "CS Tactics" },
      { site: "B", type: "molly", name: "Back Plat molotofu", yt: ["rKWeOfcTN44", 851, 863], by: "CS Tactics" },
      { site: "B", type: "molly", name: "B bölgesi molotofu", yt: ["rKWeOfcTN44", 863, 881], by: "CS Tactics" },
      { site: "Mid", type: "smoke", name: "Xbox smoke", yt: ["Bc0WFG-fU4w", 7, 22], by: "CS Tactics" },
      { site: "Mid", type: "smoke", name: "Mid to B smoke", yt: ["Bc0WFG-fU4w", 132, 155], by: "CS Tactics" },
      { site: "Mid", type: "flash", name: "Mid flash'ı", yt: ["rKWeOfcTN44", 728, 742], by: "CS Tactics" },
    ],
  },
  {
    id: "inferno",
    name: "Inferno",
    radar: "radar/inferno.png",
    summary: "Dar sokaklı İtalyan kasabası. Banana (B) ve Apartments (A) kontrolü belirleyicidir.",
    spawns: { T: [0.1, 0.67], CT: [0.9, 0.35] },
    sites: { A: [0.81, 0.69], B: [0.49, 0.22] },
    callouts: [
      { name: "T Spawn", at: [0.1, 0.6], desc: "Teröristlerin doğduğu yer." },
      { name: "T Ramp", at: [0.22, 0.72], desc: "T doğuşundan Mid ve Banana'ya giden yol." },
      { name: "Mid", at: [0.56, 0.66], desc: "Haritanın ortası; A'ya Short üzerinden gider." },
      { name: "Top Mid", at: [0.7, 0.58], desc: "Mid'in CT tarafındaki ucu." },
      { name: "Short", at: [0.73, 0.71], desc: "Mid'den A bölgesine açılan kısa yol." },
      { name: "Apartments", at: [0.6, 0.79], desc: "A'ya üst kattan giden apartman (Apps)." },
      { name: "Balcony", at: [0.73, 0.8], desc: "Apartmanın A'ya açılan balkonu." },
      { name: "A Site", at: [0.81, 0.63], desc: "A bomba bölgesi." },
      { name: "Pit", at: [0.9, 0.84], desc: "A'nın arkasındaki çukur." },
      { name: "Graveyard", at: [0.83, 0.79], desc: "Pit'in önündeki mezarlık." },
      { name: "Library", at: [0.93, 0.7], desc: "A'nın CT tarafındaki oda." },
      { name: "Arch", at: [0.87, 0.53], desc: "A'yı CT'ye bağlayan kemer." },
      { name: "Banana", at: [0.47, 0.47], desc: "B'ye giden uzun, kıvrımlı yol." },
      { name: "Car", at: [0.52, 0.36], desc: "Banana'nın sonundaki araba; B'ye giriş." },
      { name: "B Site", at: [0.49, 0.17], desc: "B bomba bölgesi." },
      { name: "Dark", at: [0.44, 0.11], desc: "B'nin arka köşesi." },
      { name: "Coffins", at: [0.57, 0.22], desc: "B'nin CT tarafındaki tabutlar." },
      { name: "CT", at: [0.7, 0.22], desc: "B'yi CT doğuşuna bağlayan yol." },
    ],
    lineups: [
      { site: "A", type: "smoke", name: "Arch smoke", yt: ["bCuck5TrjyU", 313, 330], by: "Tigerr" },
      { site: "A", type: "smoke", name: "Library smoke", yt: ["bCuck5TrjyU", 330, 361], by: "Tigerr" },
      { site: "A", type: "smoke", name: "Moto smoke", yt: ["bCuck5TrjyU", 361, 391], by: "Tigerr" },
      { site: "A", type: "smoke", name: "Arch + Library tek noktadan", yt: ["xBVKvESvv2U", 63, 93], by: "GettClutch" },
      { site: "A", type: "flash", name: "A bölgesi flash'ı", yt: ["bCuck5TrjyU", 391, 449], by: "Tigerr" },
      { site: "A", type: "flash", name: "Apartments flash'ı", yt: ["bCuck5TrjyU", 449, 466], by: "Tigerr" },
      { site: "B", type: "smoke", name: "CT smoke", yt: ["bCuck5TrjyU", 50, 81], by: "Tigerr" },
      { site: "B", type: "smoke", name: "Coffins smoke", yt: ["bCuck5TrjyU", 81, 106], by: "Tigerr" },
      { site: "B", type: "flash", name: "Banana flash'ı", yt: ["bCuck5TrjyU", 13, 50], by: "Tigerr" },
      { site: "B", type: "flash", name: "B bölgesi flash'ı", yt: ["bCuck5TrjyU", 147, 159], by: "Tigerr" },
      { site: "B", type: "molly", name: "B kutularına molotof", yt: ["bCuck5TrjyU", 106, 147], by: "Tigerr" },
      { site: "Mid", type: "smoke", name: "Top Mid smoke", yt: ["bCuck5TrjyU", 274, 313], by: "Tigerr" },
    ],
  },
];
