// CS2 haritaları: infolar (callout) ve bomba taktikleri.
// Konumlar radar görüntüsü üzerinde 0–1 arası oran olarak (x: soldan, y: üstten).
// Doğuş ve bomba bölgesi konumları oyunun radar dosyalarından alınmıştır.

const CS2_MAPS = [
  {
    id: "mirage",
    name: "Mirage",
    radar: "radar/mirage.png",
    summary: "Fas temalı klasik harita. Orta (Mid) kontrolü iki bölgeyi de açar.",
    spawns: { T: [0.87, 0.36], CT: [0.28, 0.7] },
    sites: { A: [0.54, 0.76], B: [0.23, 0.28] },
    callouts: [
      { name: "T Spawn", at: [0.88, 0.3], desc: "Teröristlerin doğduğu yer." },
      { name: "T Ramp", at: [0.84, 0.57], desc: "T doğuşundan A'ya inen yol." },
      { name: "A Ramp", at: [0.72, 0.66], desc: "Ramp'in A bölgesine açılan ucu." },
      { name: "Palace", at: [0.76, 0.76], desc: "A'ya güneyden açılan bina; balkondan A görülür." },
      { name: "Tetris", at: [0.62, 0.66], desc: "Ramp'in sonundaki kutular; A'ya girişte ilk saklanma yeri." },
      { name: "Ninja", at: [0.6, 0.83], desc: "A bölgesinin Palace tarafındaki gizli köşe." },
      { name: "Firebox", at: [0.46, 0.83], desc: "A bölgesinin CT tarafındaki kutu." },
      { name: "Stairs", at: [0.48, 0.7], desc: "A'dan Jungle ve Connector'a çıkan merdiven." },
      { name: "Jungle", at: [0.42, 0.6], desc: "A'nın kuzeybatısındaki oda; CT'lerin A savunma yeri." },
      { name: "Ticket Booth", at: [0.39, 0.8], desc: "CT ile A arasındaki bilet gişesi." },
      { name: "Connector", at: [0.51, 0.57], desc: "Mid'i Jungle ve A'ya bağlayan koridor." },
      { name: "Top Mid", at: [0.68, 0.42], desc: "Mid'in T tarafındaki girişi." },
      { name: "Mid", at: [0.56, 0.47], desc: "Haritanın ortası; A ve B arasında geçiş sağlar." },
      { name: "Window", at: [0.43, 0.44], desc: "Mid'e bakan keskin nişancı penceresi." },
      { name: "Short", at: [0.5, 0.24], desc: "Mid'den B'ye giden kısa yol (Catwalk)." },
      { name: "B Apps", at: [0.38, 0.18], desc: "B'ye giden apartman koridoru." },
      { name: "Van", at: [0.17, 0.22], desc: "B bölgesindeki minibüs; Apps çıkışını kontrol eder." },
      { name: "Market", at: [0.25, 0.45], desc: "B ile CT arasındaki dükkân." },
    ],
    tactics: [
      {
        site: "A",
        title: "A girişi (Ramp + Palace)",
        steps: [
          "Ramp'ten CT, Jungle ve Stairs smoke'ları atılır; A'nın CT tarafı kapanır.",
          "Palace'tan Firebox'a molotof, A'nın üstüne flash atılır.",
          "Ramp ve Palace grupları aynı anda girer; bir oyuncu Connector'ı tutar.",
          "Bomba Default'a kurulur; Palace, Ramp ve Connector'dan korunur.",
        ],
        smokes: [[0.4, 0.76], [0.43, 0.6], [0.48, 0.67]],
        mollies: [[0.47, 0.81]],
        flashes: [[0.55, 0.72]],
        routes: [
          [[0.86, 0.5], [0.84, 0.58], [0.78, 0.62], [0.71, 0.66], [0.59, 0.72]],
          [[0.88, 0.58], [0.83, 0.68], [0.78, 0.75], [0.64, 0.76], [0.57, 0.79]],
          [[0.82, 0.38], [0.68, 0.43], [0.55, 0.5], [0.51, 0.56]],
        ],
        plant: [0.53, 0.76],
      },
      {
        site: "B",
        title: "B girişi (Apps + Short)",
        steps: [
          "Market penceresi ve Market kapısına smoke atılır; CT'den gelen destek gecikir.",
          "Van ve Bench'e molotof, Apps çıkışından B'ye flash atılır.",
          "Apps grubu çıkarken bir oyuncu Short'tan girer.",
          "Bomba B'nin ortasına kurulur; Apps, Short ve Market'e bakılır.",
        ],
        smokes: [[0.24, 0.39], [0.28, 0.44]],
        mollies: [[0.18, 0.22], [0.2, 0.34]],
        flashes: [[0.26, 0.24]],
        routes: [
          [[0.58, 0.2], [0.45, 0.18], [0.33, 0.19], [0.26, 0.25]],
          [[0.82, 0.38], [0.66, 0.36], [0.55, 0.25], [0.4, 0.26], [0.3, 0.28]],
        ],
        plant: [0.23, 0.28],
      },
    ],
  },
  {
    id: "dust2",
    name: "Dust 2",
    radar: "radar/dust2.png",
    summary: "En bilinen harita. Uzun koridorlar ve net bölgeler; Long ve Tunnels kontrolü önemli.",
    spawns: { T: [0.39, 0.91], CT: [0.62, 0.21] },
    sites: { A: [0.8, 0.16], B: [0.21, 0.12] },
    callouts: [
      { name: "T Spawn", at: [0.38, 0.86], desc: "Teröristlerin doğduğu yer." },
      { name: "Outside Long", at: [0.61, 0.78], desc: "T doğuşundan Long kapılarına giden açık alan." },
      { name: "Long Doors", at: [0.7, 0.61], desc: "Long'a açılan çift kapı." },
      { name: "Pit", at: [0.88, 0.63], desc: "Long'un sonundaki çukur; A'ya bakan sniper yeri." },
      { name: "Long A", at: [0.88, 0.44], desc: "A bölgesine giden uzun koridor." },
      { name: "A Car", at: [0.92, 0.29], desc: "Long'un A'ya açıldığı yerdeki araba." },
      { name: "Goose", at: [0.86, 0.09], desc: "A bölgesinin arka köşesi." },
      { name: "Short", at: [0.59, 0.37], desc: "Mid'den A'ya çıkan merdivenli yol (Catwalk)." },
      { name: "Mid", at: [0.47, 0.55], desc: "Haritanın ortası; Short ve B'ye geçiş sağlar." },
      { name: "Xbox", at: [0.49, 0.42], desc: "Mid'deki büyük kutu; Short'a çıkışta kullanılır." },
      { name: "Mid Doors", at: [0.46, 0.31], desc: "Mid'i CT'ye bağlayan kapılar." },
      { name: "Top Mid", at: [0.46, 0.72], desc: "Mid'in T tarafındaki girişi." },
      { name: "Lower Tunnels", at: [0.33, 0.4], desc: "Mid'den B tünellerine giden alt tünel." },
      { name: "Upper Tunnels", at: [0.15, 0.45], desc: "B'ye açılan üst tünel." },
      { name: "Outside Tunnels", at: [0.15, 0.7], desc: "T doğuşundan tünellere giden yol." },
      { name: "B Doors", at: [0.25, 0.23], desc: "B'yi CT tarafına bağlayan kapı." },
      { name: "Window", at: [0.27, 0.12], desc: "B bölgesine CT tarafından bakan pencere." },
      { name: "Back Plat", at: [0.11, 0.05], desc: "B bölgesinin en arkası." },
    ],
    tactics: [
      {
        site: "A",
        title: "A girişi (Long + Short)",
        steps: [
          "CT ve Cross smoke'ları atılır; CT'den Long'a bakış kapanır.",
          "Long köşesine flash atılıp Long A'dan ilerlenir.",
          "Bir-iki oyuncu Xbox üzerinden Short'tan aynı anda girer.",
          "Bomba A'nın ortasına kurulur; Long, Short ve CT'ye bakılır.",
        ],
        smokes: [[0.7, 0.18], [0.85, 0.27]],
        mollies: [[0.84, 0.1]],
        flashes: [[0.88, 0.36]],
        routes: [
          [[0.42, 0.88], [0.58, 0.8], [0.66, 0.68], [0.75, 0.58], [0.88, 0.5], [0.88, 0.32], [0.82, 0.2]],
          [[0.42, 0.85], [0.46, 0.65], [0.49, 0.46], [0.58, 0.39], [0.64, 0.28], [0.75, 0.2]],
        ],
        plant: [0.79, 0.16],
      },
      {
        site: "B",
        title: "B girişi (Tunnels)",
        steps: [
          "B Doors ve Window'a smoke atılır; CT'den gelen destek ve görüş kapanır.",
          "Back Plat'a molotof, tünel çıkışından B'ye flash atılır.",
          "Takım Upper Tunnels'tan hızlıca çıkıp B'ye yayılır.",
          "Bomba B'nin ortasına kurulur; Doors, Window ve Tunnels'a bakılır.",
        ],
        smokes: [[0.25, 0.22], [0.27, 0.12]],
        mollies: [[0.12, 0.06]],
        flashes: [[0.15, 0.2]],
        routes: [[[0.36, 0.88], [0.18, 0.78], [0.15, 0.6], [0.15, 0.45], [0.11, 0.32], [0.18, 0.16]]],
        plant: [0.2, 0.12],
      },
    ],
  },
  {
    id: "inferno",
    name: "Inferno",
    radar: "radar/inferno.png",
    summary: "Dar sokaklı İtalyan kasabası. Banana (B) ve Apartments (A) kontrolü belirleyicidir.",
    spawns: { T: [0.1, 0.67], CT: [0.9, 0.35] },
    sites: { A: [0.81, 0.69], B: [0.49, 0.22] },
    callouts: [
      { name: "T Spawn", at: [0.1, 0.6], desc: "Teröristlerin doğduğu yer." },
      { name: "T Ramp", at: [0.22, 0.72], desc: "T doğuşundan Mid ve Banana'ya giden yol." },
      { name: "Mid", at: [0.56, 0.66], desc: "Haritanın ortası; A'ya Short üzerinden gider." },
      { name: "Top Mid", at: [0.7, 0.58], desc: "Mid'in CT tarafındaki ucu." },
      { name: "Short", at: [0.73, 0.71], desc: "Mid'den A bölgesine açılan kısa yol." },
      { name: "Apartments", at: [0.6, 0.79], desc: "A'ya üst kattan giden apartman (Apps)." },
      { name: "Balcony", at: [0.73, 0.8], desc: "Apartmanın A'ya açılan balkonu." },
      { name: "A Site", at: [0.81, 0.63], desc: "A bomba bölgesi." },
      { name: "Pit", at: [0.9, 0.84], desc: "A'nın arkasındaki çukur." },
      { name: "Graveyard", at: [0.83, 0.79], desc: "Pit'in önündeki mezarlık." },
      { name: "Library", at: [0.93, 0.7], desc: "A'nın CT tarafındaki oda." },
      { name: "Arch", at: [0.87, 0.53], desc: "A'yı CT'ye bağlayan kemer." },
      { name: "Banana", at: [0.47, 0.47], desc: "B'ye giden uzun, kıvrımlı yol." },
      { name: "Car", at: [0.52, 0.36], desc: "Banana'nın sonundaki araba; B'ye giriş." },
      { name: "B Site", at: [0.49, 0.17], desc: "B bomba bölgesi." },
      { name: "Dark", at: [0.44, 0.11], desc: "B'nin arka köşesi." },
      { name: "Coffins", at: [0.57, 0.22], desc: "B'nin CT tarafındaki tabutlar." },
      { name: "CT", at: [0.7, 0.22], desc: "B'yi CT doğuşuna bağlayan yol." },
    ],
    tactics: [
      {
        site: "A",
        title: "A girişi (Apartments + Short)",
        steps: [
          "Arch ve Library'ye smoke atılır; CT'den A'ya gelen destek kapanır.",
          "Pit'e molotof, Balcony'den A'ya flash atılır.",
          "Apartments grubu Balcony'den, bir-iki oyuncu Short'tan aynı anda girer.",
          "Bomba A'nın ortasına kurulur; Arch, Library ve Pit'e bakılır.",
        ],
        smokes: [[0.87, 0.55], [0.92, 0.68]],
        mollies: [[0.9, 0.82]],
        flashes: [[0.8, 0.73]],
        routes: [
          [[0.15, 0.7], [0.3, 0.75], [0.45, 0.76], [0.6, 0.79], [0.72, 0.8], [0.79, 0.72]],
          [[0.15, 0.66], [0.35, 0.65], [0.55, 0.66], [0.7, 0.68], [0.78, 0.68]],
        ],
        plant: [0.81, 0.69],
      },
      {
        site: "B",
        title: "B girişi (Banana)",
        steps: [
          "CT ve Coffins'e smoke atılır; CT'den B'ye bakış kapanır.",
          "Dark'a molotof, Car'ın üstünden B'ye flash atılır.",
          "Takım Banana'dan Car'a kadar ilerleyip B'ye birlikte girer.",
          "Bomba B'nin ortasına kurulur; Banana, CT ve Dark'a bakılır.",
        ],
        smokes: [[0.66, 0.22], [0.57, 0.2]],
        mollies: [[0.44, 0.12]],
        flashes: [[0.5, 0.28]],
        routes: [[[0.15, 0.66], [0.3, 0.64], [0.43, 0.6], [0.46, 0.48], [0.5, 0.38], [0.5, 0.26]]],
        plant: [0.49, 0.22],
      },
    ],
  },
];
