// Rainbow Six Siege: Türkçe metinler. Operatör ve harita adları, yetenek/ekipman adları oyundaki gibi İngilizce kalır.
// R6_TR.abilities: özel yeteneğin kısa Türkçe anlatımı (wikideki ayrıntılı İngilizce metin sayfada ayrıca açılabilir).
// R6_TR.maps: haritanın kısa tanıtımı. R6_TR.roles / weaponTypes / sides: etiketler.
const R6_TR = {
  sides: { Attacker: "Saldırı", Defender: "Savunma" },
  roles: {
    "Front Line": "Ön hat",
    "Back Line": "Arka hat",
    "Anti-Entry": "Giriş engelleme",
    "Anti-Gadget": "Gadget karşıtı",
    "Anti-Roam": "Roam karşıtı",
    "Anti-Hard Breach": "Hard breach engelleme",
    "Area Denial": "Alan kapatma",
    Breach: "Breach",
    "Crowd Control": "Kalabalık kontrolü",
    Disable: "Gadget bozma",
    "Entry Fragger": "Entry fragger",
    Flank: "Flank",
    "Hard Breach": "Hard breach",
    Heal: "İyileştirme",
    Intel: "Bilgi toplama",
    "Intel Denial": "Bilgi engelleme",
    "Map Control": "Harita kontrolü",
    Roam: "Roam",
    Secure: "Bölge tutma",
    "Soft Breach": "Soft breach",
    Support: "Destek",
    Trap: "Tuzak",
    Anchor: "Anchor",
  },
  weaponTypes: {
    "Assault Rifle": "Taarruz tüfeği",
    "Submachine Gun": "Hafif makineli (SMG)",
    "Light Machine Gun": "Ağır makineli (LMG)",
    "Marksman Rifle": "Nişancı tüfeği (DMR)",
    Shotgun: "Pompalı",
    Handgun: "Tabanca",
    Pistol: "Tabanca",
    Revolver: "Revolver",
    "Hand Cannon": "Hand cannon",
    "Machine Pistol": "Makineli tabanca",
    "Ballistic Shield": "Kalkan",
    "Electric Shield": "Elektrikli kalkan",
  },
  abilities: {
    ace: "S.E.L.M.A. su bazlı breach cihazını güçlendirilmiş (reinforced) duvara atar; cihaz duvarda aşağı doğru kayarak iki kez patlar ve geçilebilecek büyük bir delik açar. Hatch'leri de kırabilir (güçlendirilmiş hatch için iki tane gerekir).",
    alibi: "Prisma ile kendisinin hologram kopyasını yere atar. Kopyaya ateş eden ya da içinden geçen saldırgan birkaç saniyeliğine işaretlenir ve yeri görünür.",
    amaru: "Garra Hook ile pencerelere, açık hatch'lere ve çatı kenarlarına kanca atıp kendini hızla oraya çeker. Beklenmedik açılardan ve yukarıdan hızlı giriş yapar.",
    aruni: "Surya Laser Gate'i kapı, pencere ya da duvar deliğine kurar. Lazer geçen saldırgana hasar verir, içinden geçen drone ve fırlatılan gadget'ları yok eder; savunmacılar yaklaşınca kısa süre kapanır. Elleriyle tek yumrukta barikat ve yumuşak duvarlarda delik açabilir.",
    ash: "M120 CREM ile uzaktan Breaching Round atar: mermi yumuşak duvara, barikata ya da zemine saplanıp kısa süre sonra patlar ve geniş bir delik açar. Savunmacının gadget'larını da uzaktan yok eder.",
    azami: "Kiba Barrier bıçaklarını atar; köpük genişleyip kurşun geçirmez bir engele dönüşür. Delikleri, pencereleri ve açılan breach'leri kapatır ya da kendine siper yapar.",
    bandit: "Shock Wire'ı güçlendirilmiş duvara, barikat telinin yanına ya da deployable shield'a takar; elektrik Thermite, Hibana ve benzeri hard breach gadget'larını, drone'ları ve dokunan saldırganı yakar.",
    blackbeard: "H.U.L.L. Adaptable Shield'ı silahına takar; nişan alırken üst gövdesini korur ve rappel'deyken pencereden bakarken de koruma sağlar.",
    blitz: "G52-Tactical Shield ile ilerler; kalkanın flaşı yakındaki rakipleri bir süre kör eder. Kalkan açıkken yalnızca tabancasını kullanabilir.",
    brava: "Kludge Drone ile savunmacının elektronik gadget'larını uzaktan hack'ler. Kameralar onun takımına geçer, bazı gadget'lar (ör. Kapkan, Mute) kendini yok eder, bazıları ters çalışır.",
    buck: "Skeleton Key alt namlu pompalısıyla tavanları, zeminleri ve yumuşak duvarları kolayca deler; yukarıdan ya da aşağıdan savunmacıların açılarını kırar.",
    capitao: "Taktik arbaletiyle iki tür ok atar: yangın oku bölgeyi alevle kapatır, duman oku görüşü kapatır. Defuser kurarken ya da savunmacıyı yerinden çıkarmak için kullanılır.",
    castle: "Armor Panel'i kapı ve pencerelere kurar; kurşun geçirmez panel saldırganların giriş yolunu kapatır. Patlayıcı ya da bazı gadget'larla kırılabilir.",
    caveira: "Silent Step ile ayak sesi çıkarmadan hareket eder. Yere düşürdüğü saldırganı sorgulayarak tüm saldırı takımının yerini birkaç saniye görünür kılar.",
    clash: "CCE Shield ile koridorları tutar; kalkanın şok tabancası önündeki saldırganları yavaşlatır ve hasar verir. Kalkan açıkken yalnızca tabanca kullanılabilir, arkası korumasızdır.",
    deimos: "DeathMARK ile işaretlediği bir savunmacının yerini sürekli takip eder. Takip sırasında .44 Vendetta revolver'ını kullanır; hedef de Deimos'un yerini görür.",
    denari: "T.R.I.P. Connector'ları duvarlara yerleştirir; görüş hattındaki iki connector arasında lazer oluşur. Lazere değen saldırgan her lazer için hasar alır ve yavaşlar, savunmacılar zarar görmez.",
    doc: "Stim Pistol ile kendini ya da takım arkadaşlarını uzaktan iyileştirir, düşmüş arkadaşını kaldırır ve geçici olarak ek can verir.",
    dokkaebi: "Logic Bomb ile savunmacıların telefonlarını çaldırır; çalan telefon sesiyle yerlerini belli eder. Düşürdüğü savunmacının telefonuyla kameralara erişebilir.",
    echo: "Yokai drone'unu tavana yapıştırır; görünmez hâldeyken saldırganları ses dalgasıyla sersemletir ve defuser kurulmasını engeller.",
    ela: "Grzmot Mine'ları yerleştirir; saldırgan yaklaşınca patlayan mayın onu sarsar ve kısa süre yavaşlatır, görüşünü bozar.",
    fenrir: "F-NATT Dread Mine'ları duvara ya da zemine atar ve uzaktan etkinleştirir. Saldırgan menzile girince mayın görüşü bozan korku gazı salar.",
    finka: "Adrenal Surge ile tüm takımına geçici ek can verir, düşmüş arkadaşlarını kaldırır, sersemleme ve benzeri etkileri azaltır.",
    flores: "RCE-Ratero patlayıcı drone'larını sürer; drone savunmacının gadget'larının ve kendisinin yanına gidip patlar.",
    frost: "Welcome Mat ayı kapanlarını kapı önlerine, pencere altlarına ve breach çıkışlarına koyar. Basan saldırgan yere düşer ve kurtarılmazsa ölür.",
    fuze: "Cluster Charge'ı yumuşak ya da güçlendirilmiş duvara, zemine yerleştirir; içeri art arda küçük bombalar atarak odadaki savunmacılara ve gadget'lara hasar verir.",
    glaz: "Flip Sight dürbünü ve keskin nişancı tüfeğiyle uzaktan oynar; dürbün duman içindeki rakipleri ısıyla gösterir.",
    goyo: "Volcán Canister'larını yerleştirir; vurulunca patlayan kutu alanı bir süre ateşle kapatır.",
    gridlock: "Trax Stingers'ı atar; zemine yayılan dikenli paneller savunmacıları yavaşlatır, hasar verir ve üstüne basıldığında ses çıkarır. Flank yollarını kapatmak için idealdir.",
    grim: "Kawan Hive Launcher ile bölgeye mikro drone sürüsü atar; sürüye giren savunmacılar işaretlenir ve yerleri takım tarafından görülür.",
    hibana: "X-KAIROS ile güçlendirilmiş duvar ve hatch'lere patlayıcı peletler atar, uzaktan patlatarak küçük delikler ya da geçilebilir bir açıklık oluşturur.",
    iana: "Gemini Replicator ile kendinin hologram kopyasını oluşturur ve drone gibi uzaktan yönetir; savunmacıların yerini ve tuzakları güvenle keşfeder.",
    iq: "Electronics Detector ile duvarların arkasındaki savunma gadget'larını görür ve yok eder.",
    jackal: "Eyenox ile savunmacıların ayak izlerini görür ve tarar; izi taranan savunmacının yeri birkaç kez takıma bildirilir.",
    jager: "Active Defense System (ADS) cihazlarını kurar; savunmaya atılan el bombalarını ve patlayıcıları havada vurup yok eder.",
    kaid: "Rtila Electroclaw'ı atar; çevresindeki güçlendirilmiş duvarları, hatch'leri, barikatları ve deployable shield'ları elektriklendirerek hard breach'i engeller.",
    kali: "CSRX 300 keskin nişancı tüfeğiyle tek atışta yumuşak duvarları delip savunmacıları düşürür. LV Explosive Lance ile duvarların arkasındaki savunma gadget'larını yok eder.",
    kapkan: "Entry Denial Device (EDD) tuzaklarını kapı ve pencere kenarlarına kurar; geçen saldırgana patlayarak hasar verir.",
    lesion: "Gu mayınlarını yere atar; görünmez mayına basan saldırgan zehirlenir, yavaşlar ve iğneyi çıkarana kadar hasar alır.",
    lion: "EE-ONE-D drone'unu kullanır; tarama sırasında hareket eden savunmacıların yerleri tüm takıma gösterilir.",
    maestro: "Evil Eye kameralarını kurar; kurşun geçirmez kameralar lazerle ateş edebilir. Ateş ederken camı açılır ve kırılabilir.",
    maverick: "Breaching Torch ile güçlendirilmiş duvarlarda sessizce küçük delikler açar; duvarı tamamen kesip geçilebilir hâle de getirebilir.",
    melusi: "Banshee Sonic Defense cihazlarını kurar; menzile giren saldırgan yavaşlar ve cihaz ses çıkararak yerini belli eder.",
    mira: "Black Mirror'ı güçlendirilmiş duvara takar; tek yönlü kurşun geçirmez cam sayesinde savunmacılar dışarıyı görür, saldırganlar içeriyi zor görür.",
    montagne: "Le Roc kalkanını açarak neredeyse tamamen korunur; takımına siper olur ve bilgi toplar. Kalkan tam açıkken ateş edemez.",
    mozzie: "Pest Launcher ile saldırganların drone'larını hack'leyip ele geçirir ve onları savunma için kullanır.",
    mute: "Signal Disruptor'ları yerleştirir; menzilindeki drone'ları, hard breach şarjlarını ve uzaktan patlatılan gadget'ları susturur.",
    nokk: "HEL Presence Reduction ile kameralarda görünmez olur ve ayak sesini azaltır; savunmacıları arkadan yakalar.",
    nomad: "Airjab Launcher ile flank yollarına mayın atar; mayına giren savunmacılar savrularak yere düşer.",
    noor: "Horus Lance Launcher ile duvar ve zeminlere mızrak atar; mızrak içine saplanıp iki taraftan alev püskürterek alanı kapatır. Kalkanlara karşı özellikle etkilidir.",
    oryx: "Remah Dash ile hızla atılarak yumuşak duvarları ve barikatları kırar, saldırganları yere serer. Açık hatch'lerden yukarı kat tırmanabilir.",
    osa: "Talon-8 Clear Shield'ı taşır ya da kapı ve pencerelere kurar; şeffaf kurşun geçirmez kalkan görüşü kapatmadan siper sağlar.",
    pulse: "Heartbeat Sensor ile duvar ve zeminlerin arkasındaki saldırganların kalp atışlarını algılar.",
    ram: "BU-GI Auto-Breacher'ı ileri sürer; robot yoluna çıkan yumuşak duvarları, zeminleri ve gadget'ları kırarak büyük açıklıklar oluşturur.",
    rauora: "D.O.M. Panel Launcher ile kapı boşluklarına kurşun geçirmez panel fırlatır; panel kapıyı tamamen kapatıp saldırganlara siper sağlar ve flank yollarını keser.",
    rook: "Armor Pack kutusunu bırakır; takım arkadaşları zırh plakası alarak ek can kazanır ve düşünce bayılmadan önce dayanma şansı artar.",
    sens: "R.O.U. Projector'ı yuvarlar; geçtiği hat boyunca ışık duvarı oluşturarak görüşü kapatır. Savunmacının açılarını kapatmak ve güvenle geçmek için kullanılır.",
    sentry: "Özel bir yeteneği yoktur; bunun yerine iki farklı savunma ikincil gadget'ını birlikte taşır (Gadget Kit).",
    skopos: "V10 Pantheon Shells: iki insansı robotu uzaktan yönetir. Aynı anda biri kontrol edilir; diğeri kalkan açıp çömelerek bekler. Robotlar ateş edebilir ve gadget kullanabilir.",
    sledge: "Tactical Breaching Hammer ile yumuşak duvarları, zeminleri, barikatları ve hatch'leri sessizce kırar.",
    smoke: "Remote Gas Grenade'leri yerleştirip uzaktan patlatır; zehirli gaz bölgeyi saldırganlara kapatır.",
    solidsnake: "Soliton Radar MKIII ile yakınındaki düşmanları ve kameraları radarda görür; hassas modda düşmanların baktığı yönü de gösterir. Yerdeki el bombalarını ve şarjları toplayabilir.",
    solis: "SPEC-IO Electro Sensor ile saldırganların elektronik cihazlarını (drone, telefon vb.) duvarların arkasından görür.",
    striker: "Özel bir yeteneği yoktur; bunun yerine iki farklı saldırı ikincil gadget'ını birlikte taşır (Gadget Kit).",
    tachanka: "Shumikha Launcher ile yangın bombası atar; alev alanı saldırganları yakar ve yerinden çıkarır.",
    thatcher: "EMP Grenade'iyle çevredeki elektronik savunma gadget'larını (Bandit, Kaid, kameralar vb.) devre dışı bırakır.",
    thermite: "Exothermic Charge ile güçlendirilmiş duvarları eriterek büyük, geçilebilir bir delik açar.",
    thorn: "Razorbloom Shell'i yüzeylere yapıştırır; menzile giren saldırgan kısa bir gecikmeden sonra patlayarak hasar alır.",
    thunderbird: "Kóna Station'ı kurar; istasyon yakındaki yaralı takım arkadaşlarını iyileştirir ve düşmüşleri kaldırır.",
    tubarao: "Zoto Canister'ı atar; dondurduğu alandaki saldırgan gadget'larını bir süre durdurur, saldırganları yavaşlatır ve ayak izlerini bırakır.",
    twitch: "Shock Drone ile savunmacının gadget'larını ateşle yok eder ve savunmacılara hasar verir.",
    valkyrie: "Black Eye kameralarını haritanın istediği yerine atar ve savunma için ek kamera ağı kurar.",
    vigil: "ERC-7 ile drone ve kamera görüntülerinden silinir; saldırganlara görünmeden roam yapar.",
    wamai: "Mag-NET'leri kurar; çevresine atılan el bombası ve patlayıcıları kendine çekip patlatır, bazen saldırganın kendisine karşı çevirir.",
    warden: "Glance Smart Glasses ile flaş ve dumanın içini görür; flaş etkisinden korunur.",
    ying: "Candela'yı atar; art arda patlayan flaşlar odadaki savunmacıları kör eder.",
    zero: "ARGUS Launcher ile duvarlara kamera atar; kamera duvarın iki tarafını görür ve savunmacının gadget'larını lazerle yok edebilir.",
    zofia: "KS79 Lifeline ile darbe ve sersemletme el bombası atar. Yere düştüğünde kendini kaldırabilir.",
  },
  maps: {
    bank: "Los Angeles'ta sıkı korunan büyük bir banka. Bodrum, iki kat ve çatı; savunmacılar küçük odaları kolayca güçlendirir, saldırganlar binaya kat kat ilerler.",
    bartlettu: "Cambridge, Massachusetts'te bir üniversite. Birbirinden çok farklı iki kat; küçük, yakın mesafe çatışmaya dayalı bir harita.",
    border: "Orta Doğu'da bir sınır kapısı. Eski ve yeni yapılar ile açık hava geçitleri; binanın ortasındaki geçitler iki tarafı birbirine bağlar.",
    calypsocasino: "Las Vegas'ta bir kumarhane. Rainbow Six: Vegas'taki aynı adlı haritadan uyarlanan yeni bir harita.",
    chalet: "Fransız Alpleri'nde (Courchevel) bir dağ evi. Sıcak iç mekânlar ve görüşün kısıtlı olduğu karlı dış alan.",
    clubhouse: "Almanya'nın Hannover şehrinde bir motorcu çetesinin merkezi. Bodrum, iki kat ve çatı; çok sayıda dönüş yolu ve kırılabilir zemin.",
    coastline: "İspanya'nın İbiza adasında renkli bir gece kulübü kompleksi. Çok sayıda oda ve pencere.",
    consulate: "Fildişi Sahili'nde (Abidjan) bir Fransız konsolosluğu. Çok sayıda penceresi olan, sıkı korunan bir bina.",
    district: "Detroit'te bir şehir bölgesi. Yalnızca 6v6 Dual Front modunda oynanır; dış alanlar da oynanabilir.",
    emeraldplains: "Kuzey İrlanda'da bir kır kulübü ve özel çiftlik. Büyük ve açık alanlı bir harita; sabır ve dikkat ister.",
    favela: "Brezilya'da (Rio de Janeiro) bir gecekondu mahallesi. Dar sokaklar, çok sayıda oda ve kırılabilir dış cepheler.",
    fortress: "Fas'ta Atlas Dağları'nda bir kasbah (kale). Avlular ve dar koridorlar.",
    herefordbaserework: "İngiltere'de SAS'ın eğitim üssü. Bodrum, üç kat ve çatı; yenilenen hâlinde daha çok kırılabilir zemin ve merdiven var.",
    house: "Los Angeles'ta sıradan bir banliyö evi. Küçük ve hızlı oynanan, yıkılabilirliği bol bir harita.",
    kafedostoyevsky: "Moskova'nın merkezinde lüks bir kafe. Üç kat; üst katlarda sıkışık odalar ve çok sayıda kırılabilir zemin.",
    kanal: "Almanya'da (Hamburg) bir kanalın iki yakasındaki binalar. Binalar kanal üzerindeki geçitlerle birbirine bağlıdır.",
    lair: "Keres Legion'ın Portekiz'deki gizli mağara üssü. Kat geçişleri (dikey oyun) çok önemlidir.",
    nighthavenlabs: "Singapur'da Nighthaven'ın merkezi. Çok sayıda giriş ve breach noktası; bir yeri uzun süre tutmak zordur.",
    oregon: "ABD'de (Redmond, Oregon) bir sığınak kompleksi. Dar hedef odaları ve çok sayıda yumuşak duvar.",
    outback: "Avustralya'nın ıssız bir yolunda servis istasyonu, motel ve restoran. Açık dış alanlar.",
    presidentialplane: "Londra Heathrow Havalimanı'nda başkanlık uçağı. Dar, sıkışık ve breach imkânı az bir harita.",
    skyscraper: "Japonya'da (Nagoya) bir gökdelenin tepesindeki Yakuza malikânesi. İki kat; avlular ve balkonlar.",
    stadium: "Yunanistan'da (Elis) bir stadyum. Etkinliklerle gelen harita.",
    themepark: "Hong Kong'da (Kowloon) terk edilmiş bir lunapark; içinde gizli bir laboratuvar var. Uzun görüş hatları.",
    tower: "Seul'deki Mok Myeok Kulesi'nin tepesinde kurtarma görevi. Rappel ile yukarıdan girişler önemlidir.",
    villa: "İtalya'da (Toskana) bir mafya ailesinin lüks villası. Çok sayıda merdiven ve dönüş yolu.",
    yacht: "Kanada'da Baffin Körfezi'nde buzdağına çarpmış lüks bir yat. Dar koridorlar ve çok katlı yapı.",
  },
};
